<?php

/*
* API Response Code Constants
*/

define('API_CODE_INVALID_API_CALL', 0);
define('API_CODE_SUCCESS', 1111);
define('API_CODE_FAIL', 1002);
define('API_VALIDATION_ERROR', 1001);

define('API_SAVE_ERROR', 2001);
define('API_ALREADY_EXITST_ERROR', 2002);
define('API_CODE_MISSING_ACCESS_KEY', 9004);

define('API_CODE_NO_POST', 1112);

define('API_CODE_BLANK_PUBLIC_KEY', 9001);
define('API_CODE_INVALID_PUBLIC_KEY', 9000);

define('API_CODE_PUBLIC_KEY_FAIL', 9003);

define('API_CODE_BLANK_UUID_KEY', 8001);
define('API_CODE_UUID_KEY_FAIL', 8002);

define('API_CODE_DATA_VALIDATION_ERROR', 2002);

define('API_CODE_LOGIN_SUCCESS', 2100);
define('API_CODE_LOGIN_FAILED', 2101);
define('API_CODE_LOGOUT_FAILED', 2103);
define('API_CODE_LOGIN_SUCCESS_SOCIAL', 2102);

define('API_CODE_REGISTER_SUCCESS', 2110);
define('API_CODE_REGISTER_FAILED', 2111);
define('API_CODE_SOCIAL_REGISTER_SUCCESS', 2120);

define('API_CODE_RESET_PASSWORD_SUCCESS', 5110);
define('API_CODE_RESET_PASSWORD_FAILED', 5111);

define('API_CODE_INVALID_LOCATION', 3101);

define('API_CODE_EMAIL_ERROR', 5000);
define('API_CODE_SOMETHING_WENT_WRONG_ERROR', 1234);

define('API_CODE_POLL_REQUEST_ALREADY_SENT', 6001);
define('API_CODE_POLL_REQUEST_ALREADY_ACCEPTED', 6002);

define('API_CODE_VALIDATED_ACCOUNT_ERROR', 1000);
define('API_CODE_VALIDATED_ACCOUNT_UPDATE_SUCCES', 1001);
define('API_CODE_VALIDATED_ACCOUNT_UPDATE_ERROR', 1002);

define('API_CODE_INVALID_USER_KEY', 00000);
define('NO_RECORD_FOUND', 00001);
define('NO_GROUP_FOUND', 00002);
define('NO_GROUP_USER_FOUND', 00003);
define('POLL_DOES_NOT_EXIST', 00004);
define('USER_DOES_NOT_EXIST', 00005);

define('API_CODE_USER_FAILED', 9014);

define('API_CODE_SOCIAL_USER_NOT_FOUND', 1003);

